# -*- coding: utf-8 -*-
"""line_bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRSUiRewLXnpGjPa1-DDHhz0zXy3dukt
"""

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import  MessageEvent, TextMessage, TextSendMessage
import pya3rt
# from flask_ngrok import run_with_ngrok

app = Flask(__name__) 
# run_with_ngrok(app) 

linebot_api=LineBotApi('WMH0mzTTIjVoHghYLt88XhMDUYWk6oZTMq3jmGIYxd/Xr5GniD9f98kLCycV4OWGDm6x+zycW//i3vhtsrQ8aFeu9kifhS7WXec7KbMvplzj75CXylJX1DVOgd+1PvqkSARy/MBIiGn4eY08GDiJQQdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('d1e878036e1654de792766c3897d8f37') 

@app.route("/callback", methods=['POST']) 
def callback():
  signature = request.headers["X-Line-Signature"] 
  body = request.get_data(as_text=True) 
  app.logger.info("Request body"+body)

  try: 
      handler.handle(body, signature)
  except InvalidSignatureError:
    abort(400)
  return 'OK' 

@handler.add(MessageEvent, message=TextMessage) 
def handle_message(event):
  ai_message = talk_ai(event.message.text) 
  linebot_api.reply_message(event.reply_token, TextSendMessage(text=ai_message)) 
 

def talk_ai(text):
# def talk_ai(word):
  apikey = "DZZu41adXC43ciD67YLSHNzuO0QiRFEi"
  client = pya3rt.TalkClient(apikey)
  response = client.talk(text)
  return ((response['results'])[0])['reply']

  # reply_message = client.talk("word")
  # return reply_message['results'][0]['reply']

if __name__ == '__main__':
  app.run()